{% set name = "formulae" %}
{% set version = "0.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/formulae-{{ version }}.tar.gz
  sha256: 49586412cb7dcda90c2737b7d1bfb03deb9912867421bc082395c444cc661da2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - packaging
    - python >={{ python_min }}
    - numpy >=1.16
    - pandas >=1.0.0,<3.0.0
    - scipy >=1.5.4

test:
  imports:
    - formulae
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bambinos/formulae
  summary: An implementation of Wilkinson's formula language for statistical models à la lme4
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
