{% set name = "formulae" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/formulae-{{ version }}.tar.gz
  sha256: 228335df9907750793016dfb23a8a0cb8d6d9ce9a026bfe2b459aa19f72541d2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.16.1
    - pandas >=1.0.0
    - scipy >=1.5.4

test:
  imports:
    - formulae
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bambinos/formulae
  summary: An implementation of Wilkinson's formula language for statistical models à la lme4
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
