{% set name = "formulae" %}
{% set version = "0.5.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/formulae-{{ version }}.tar.gz
  sha256: 150c8ddf985234fb1f1f2b7471d299432efef43f54ea8524eee391b8929caa70

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=3.7
    - numpy >=1.16
    - pandas >=1.0.0
    - scipy >=1.5.4

test:
  imports:
    - formulae
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bambinos/formulae
  summary: An implementation of Wilkinson's formula language for statistical models à la lme4
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
