{% set name = "formulae" %}
{% set version = "0.5.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/formulae-{{ version }}.tar.gz
  sha256: b2d42e437cb138c2eaf8ae651bab98d27c6182f63b75bf8d3f51d873a0fe9e13

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.16
    - pandas >=1.0.0
    - scipy >=1.5.4

test:
  imports:
    - formulae
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bambinos/formulae
  summary: An implementation of Wilkinson's formula language for statistical models à la lme4
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
